### ISSUE TITLE
Getting exception when embedding server widget into website

### ISSUE THREAD

**Issue by itzteajay-glitch** [danielbrendel/steamwidgets-web#15]
This line is throwing an exception when I'm trying to load the server data for my game server onto my site. I'm able to do other widgets on my site like apps using the demo information. Love this tool and hope to leverage it on my website! :D

`bots = bots.replace(':count', json.data.bots);`

`query?type=js&module=server&version=v1:142 Uncaught TypeError: Cannot read properties of undefined (reading 'bots')
    at req.onreadystatechange (query?type=js&module=server&version=v1:142:58)
req.onreadystatechange @ query?type=js&module=server&version=v1:142
XMLHttpRequest.send (async)
setupWidget @ query?type=js&module=server&version=v1:205
connectedCallback @ query?type=js&module=server&version=v1:59`

**Comment by itzteajay-glitch** [comment]
https://gyazo.com/a49f66766b8889438ce4479c85142245

**Comment by danielbrendel** [comment]
Hi, I'm glad you like my service. 

The client javascript file queries the actual gameserver data from /api/query/server?addr=your_server_address. Can you post the server response from your browsers developer network tab? This will help in order to see what is going wrong.

Kind Regards

**Comment by itzteajay-glitch** [comment]
For v rising - vrising.echobasegaming:9876
for starbound - starbound.echobasegaming:21025

this site can see both my servers
https://starbound-servers.net/server/8010/
https://vrising-servers.net/server/546/

**Comment by itzteajay-glitch** [comment]
and if query ports are needed 9877 and 21026 respectively

**Comment by danielbrendel** [comment]
Your hostnames do not have any top-level-domain. So, they are not reachable from the internet. I don't know about the internals of the provided server browsers, but these hostnames will not work. You might want to get the actual internet IP address for your servers and use them instead (or domain names of your server provider that can be resolved from the internet).
